vich_uploader:
    db_driver: orm

    mappings:
       recipe_images:
           uri_prefix: /images/test
           upload_destination: '%kernel.project_dir%/public/images/test'
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
